
name: "release-sass"  

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout current branch
          uses: actions/checkout@v4
        - name: "Setup Node"
          uses: actions/setup-node@v4
        - run: npm install
        - run: npm run sass
        - name: Commit and push changes
          run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git add ./dist
            git commit -m "Update SASS files"
            git push
          