version: "3"

services:
  sass:
    build:
      context: .
      dockerfile: Dockerfile
    user: "1000:node"
    ports:
      - 8080:8080
    entrypoint: bash -c "npm install && npm start"
    working_dir: "/home/node/app"
    volumes:
      - ".:/home/node/app"
      - ".ssh:/home/node/.ssh"
      - "~/.gitconfig:/home/node/.gitconfig"
