version: "3"

services:
  sass:
    image: node:latest
    user: "${UID}:node"
    ports:
      - 8080:8080
    entrypoint: bash -c "npm install && npm start"
    working_dir: "/home/node/app"
    volumes:
      - ".:/home/node/app"
