#!/bin/bash

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

echo "Pushing ${current_branch}"

npm run bump-version
npm install
git commit -m "AutoBump Version" package.json package-lock.json
