
name: "release-sass"  

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout current branch
          uses: actions/checkout@v4
        - name: "Setup Node"
          uses: actions/setup-node@v4
        - name: "Install npm dependencies"
          run: npm install
        - name: "Building SASS files"
          run: npm run sass
        - name: commit built sass
          uses: actions-x/commit@v6
          with:
            email: actions@github.com
            name: Autocommiting Built CSS
            files: ./dist/*
            token: ${{ secrets.MY_SECRET_TOKEN }}
            force: true

        - name: Set release tag as date
          id: release_tag
          run: |
            VERSION=$(date +'%Y%m%d%H%M%S')
            echo "Setting release tag: $VERSION"
            echo "versionNum=${VERSION}" >> $GITHUB_OUTPUT

        - name: Tag version
          id: tag_version
          # if: github.ref == 'refs/heads/master'
          uses: mathieudutour/github-tag-action@v5.5
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            custom_tag: ${{ steps.release_tag.outputs.versionNum }}
        
        - name: Create a GitHub release
          # if: github.ref == 'refs/heads/master'
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ steps.release_tag.outputs.versionNum }}
            release_name: Release of SASS ${{ steps.get_version.outputs.versionNum }}
            body: ${{ steps.tag_version.outputs.changelog }}
