
name: "release-sass"  

on:
  push:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout current branch
          uses: actions/checkout@v4

        - name: "Setup Node"
          uses: actions/setup-node@v4
          with:
              node-version: 21

        - name: "Install npm dependencies"
          run: npm install

        - name: "Building SASS files"
          run: npm run sass

        - name: commit built sass
          uses: actions-x/commit@v6
          with:
            email: actions@github.com
            name: Autocommiting Built CSS
            files: ./dist/*
            token: ${{ secrets.MY_SECRET_TOKEN }}
            force: true

        - name: Set a blank commit for version
          uses: actions-x/commit@v6
          with:
            email: actions@github.com
            name: Autocommiting Built CSS

        - name: Set up Git Config
          run: |
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"

        - name: Run Semantic Release
          id: release
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            npx semantic-release -d
