
name: "release-sass"  

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout current branch
          uses: actions/checkout@v4

        - name: "Setup Node"
          uses: actions/setup-node@v4
          with:
              node-version: 21
        - name: "Install npm dependencies"
          run: npm install
        - name: "Building SASS files"
          run: npm run sass

        - name: commit built sass
          uses: actions-x/commit@v6
          with:
            email: actions@github.com
            name: Autocommiting Built CSS
            files: ./dist/*
            token: ${{ secrets.MY_SECRET_TOKEN }}
            force: true

        - name: Install jq
          run: sudo apt-get install jq

        - name: Set up Git Config
          run: |
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"

        - name: Run Semantic Release
          id: release
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            RELEASE_VERSION=$(npx semantic-release -d)
            echo "release_version=${RELEASE_VERSION}" >> $GITHUB_ENV

        - name: Extract Release Version
          run: echo "::set-output name=release_version::$(echo $RELEASE_VERSION | jq -r '.nextRelease.version')"

        # - name: Create a GitHub release
        #   if: github.ref == 'refs/heads/master'
        #   id: create_release
        #   uses: actions/create-release@v1
        #   env:
        #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   with:
        #     tag_name: ${{ steps.release_tag.outputs.versionNum }}
        #     release_name: Release of SASS ${{ steps.get_version.outputs.versionNum }}
        #     body: ${{ steps.tag_version.outputs.changelog }}
