
name: "release-sass"  

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout current branch
          uses: actions/checkout@v4
        - name: "Setup Node"
          uses: actions/setup-node@v4
        - run: npm install
        - run: npm run sass
        
        - name: Commit and push changes
          run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git add ./dist
            git commit -m "Update SASS files"
            git push

        - name: Set release tag as date
          id: release_tag
          run: |
            VERSION=$(date +'%Y%m%d%H%M%S')
            echo "Setting release tag: $RELEASE_TAG"
            echo "::set-output name=versionNum::${VERSION}"

        - name: Tag version
          id: tag_version
          # if: github.ref == 'refs/heads/master'
          uses: mathieudutour/github-tag-action@v5.5
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            custom_tag: ${{ steps.release_tag.outputs.versionNum }}
        
        - name: Create a GitHub release
          # if: github.ref == 'refs/heads/master'
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ steps.release_tag.outputs.versionNum }}
            release_name: Release APK ${{ steps.get_version.outputs.versionNum }}
            body: ${{ steps.tag_version.outputs.changelog }}
